/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package waterRefillPOS;

import java.awt.print.PrinterException;
import javax.swing.table.TableModel;

/**
 *
 * @author Inspiron
 */
public class printReciept extends javax.swing.JFrame {

    /**
     * Creates new form printReciept
     */
    public printReciept() {
        initComponents();
    }
    
    String ltotal;
    String lpaym;
    String lch;
    
    
     public printReciept(String total, String paym, String ch, TableModel tblmodel) throws PrinterException {
        initComponents();
        
        this.ltotal= total;
        this.lpaym= paym;
        this.lch= ch;
        
        txtprint.setText(txtprint.getText()+ "****************************************************\n");
        txtprint.setText(txtprint.getText()+ "******NERISSA'S WATER REFILL STORE******\n\n");
        txtprint.setText(txtprint.getText()+ "Product" + "\t" + "Price" + "\t" + "Total\n");
        
        for(int i=0; i<tblmodel.getRowCount(); i++)
        {
            String product = (String) tblmodel.getValueAt(i, 1);
            String price = (String) tblmodel.getValueAt(i, 2);
            int tot = (int) tblmodel.getValueAt(i, 4);
            
            txtprint.setText(txtprint.getText()+ product + "\t" + price + "\t" + tot + "\n");
            
            
        }
            
        txtprint.setText(txtprint.getText()+ "\n");
        txtprint.setText(txtprint.getText()+ "\n");
        
        txtprint.setText(txtprint.getText()+ "\t\t"+ "Total: "+ total + "\n");
        txtprint.setText(txtprint.getText()+ "\t\t"+ "Payment: "+ paym + "\n");
        txtprint.setText(txtprint.getText()+ "\t\t"+ "Change: "+ ch + "\n");
        txtprint.setText(txtprint.getText()+ "****************************************************\n");
        txtprint.setText(txtprint.getText()+ "*****************THANKYOU**********************\n");
        txtprint.setText(txtprint.getText()+ "****************************************************\n");
        
        
        txtprint.print();
        
        
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtprint = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(280, 407));

        txtprint.setColumns(20);
        txtprint.setRows(5);
        jScrollPane3.setViewportView(txtprint);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(printReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(printReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(printReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(printReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new printReciept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea txtprint;
    // End of variables declaration//GEN-END:variables
}
